import NavBar from '@/components/client/NavBar';
import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from '@/providers';
import Footer from '@/components/client/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          <main style={{ margin: '10px', padding: '5px' }}> {children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
